### ISSUE TITLE
feat: Configuring tracing/metrics environment variables for all knative functions

### ISSUE THREAD

**Issue by metacoma** [mindwm/mindwm-gitops#48]
```
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://otel-collector-opentelemetry-collector.monitoring-ng:4317
  - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
    value: http://tempo-distributor.monitoring-ng:4317/v1/traces
```

```
$ kubectl explain KnativeServing.spec.workloads.env
GROUP:      operator.knative.dev
KIND:       KnativeServing
VERSION:    v1beta1

FIELD: env <[]Object>


DESCRIPTION:
    Env overrides env vars for the containers.
    
FIELDS:
  container     <string> -required-
    The container name

  envVars       <[]Object>
    The desired EnvVarRequirements
```

**Comment by omgbebebe** [comment]
IMO Need to define `OTEL_SDK_DISABLED` and `OTEL_LOG_LEVEL` as well.

**Comment by metacoma** [comment]
Unfortunately, at this moment, there is no way to configure environment variables for user functions. The sample from the issue is related only to Knative Serving components: [Override the environment variables](https://knative.dev/docs/install/operator/configuring-serving-cr/#override-the-environment-variables).

Knative Serving [modifies](https://github.com/knative/serving/blob/c6665f15e5850a818a5cb23a5849b321db3d8cca/pkg/reconciler/revision/resources/deploy.go#L267) the function container environment only to add standard [Knative Serving variables](https://github.com/knative/serving/blob/c6665f15e5850a818a5cb23a5849b321db3d8cca/pkg/reconciler/revision/resources/env_var.go#L31):
